---
title: "National Parks"
author: "John Oatney, Gwen Wooten, Tommy Fowler"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

library(openintro) # install.packages("openintro")

devtools::install_github("wmurphyrd/fiftystater") # install.packages("devtools")
  
  library(fiftystater)

  data("fifty_states")

library(readr)
species <- read_csv("Biodiversity/species.csv")

library(readr)
parks <- read_csv("Biodiversity/parks.csv")

library(readr)
states <- read_csv("Biodiversity/states.csv")

```

## Brainstorming
  #Map of National Park locations to give background information
  ##Question of whether species are endangered and whether they are native to recognize where to allocate resources. 
  ##Where should we allocate resources based on where endangered species are and whether the species are native or invasive? 
    #Map of endangered 
    
```{r}
speciesendanger <- species %>% 
  filter(!is.na(`Conservation Status`), Occurrence != "Not Confirmed") %>% 
  filter(!Abundance %in% c("Native", "Not Native"))

speciesabundance <- species %>% 
  filter(!is.na(Abundance)) %>% 
  filter(!Abundance %in% c("Native", "Not Native")) %>% 
  group_by(Abundance, `Conservation Status`) %>% 
  summarize(count = n()) %>% 
  filter(`Conservation Status` == "Species of Concern")

speciesnew <- species %>% 
  filter(Occurrence != "Not Confirmed", !Abundance %in% c("Native", "Not Native"), !`Conservation Status` %in% c("Under Review", "In Recovery", "Extinct")) %>% 
  mutate(`Conservation Status` = case_when(`Conservation Status` %in% c("Species of Concern", "Endangered", "Threatened", "Proposed Threatened", "Proposed Endangered") ~ "Species of Concern")) %>% 
  mutate(`Conservation Status` = replace_na(`Conservation Status`, "Not of Concern")) 
```


```{r}
##Tommy

speciescount <- species %>% 
  group_by(`Park Name`) %>% 
  summarize(total= n()) %>% 
  mutate(sum(total))

head(speciescount)

native <- speciesendanger %>% 
  filter(Nativeness == "Native") %>% 
  group_by(Nativeness) %>% 
  summarize(total = n())

head(native)

not_native <- speciesendanger %>% 
  filter(Nativeness != "Native") %>% 
  group_by(Nativeness) %>% 
  summarize(total = n()) 

head(not_native)

percent_native <- native %>% 
  full_join(not_native) %>% 
  mutate(percent = (total / sum(total))*100) 

head(percent_native)



```

```{r}
#Tommy

speciesgraph <- speciesendanger %>% 
 filter(!is.na(Abundance), Abundance != 'Unknown') %>% 
  group_by(Category, Abundance) %>% 
  summarize(total = n()) %>% 
  filter(total > 10) 

graph2 <- species %>% 
 filter(!is.na(Abundance), Abundance != 'Unknown') %>% 
  filter(Occurrence != "Not Confirmed") %>% 
   group_by(Category, Abundance, `Conservation Status`) %>% 
  summarize(total = n()) %>% 
  #mutate(str_replace_all(`Conservation Status`, "(Endagered | Threatened)", "Threatened or Endagered")) %>%
  mutate(`Conservation Status` = replace_na(`Conservation Status`, "Not Threatened or Endagered")) %>% 
  filter(total > 10) 

  
ggplot(graph2) +
geom_col(aes(y = fct_reorder(Category, total), x=total, fill=`Conservation Status`), stat='identity') +
  labs(y = " ", x = "Total Count") +
  theme(panel.background = element_rect(fill = "white", colour = "white",size = 2, linetype = "solid"), panel.grid.major = element_line(size = 0.5, linetype = 'solid',colour = "white"), panel.grid.minor = element_line(size = 0.25, linetype = 'solid',colour = "white")) +
  guides(fill = guide_legend(title.position = "top", title = "Abundance"))+
  labs(title = "Plant and Animal Abundance in National Parks", subtitle = "Which threatened or endangered species has the most distinct types in National Parks?") +
  theme(legend.position = "bottom", axis.text.y = element_text(color = "grey27"),axis.text.x = element_text(size = 10, color = "grey27"), axis.ticks.y = element_blank(), plot.background = element_rect(fill ="peachpuff"), plot.title = element_text(face = "bold", size = 17, hjust = 1.52, color = "grey27"), plot.subtitle = element_text(face = "italic", size = 10, hjust = 1.35, color = "grey27"), plot.caption = element_text(face = "italic", color = "grey27")) +
  theme(axis.title.y=element_text(colour="grey27", face = "bold")) +
   theme(axis.title.x=element_text(colour="grey27", face = "bold")) 

ggplot(speciesgraph) +
geom_col(aes(y = fct_reorder(Category, total), fill=factor(Abundance, levels = c("Rare", "Uncommon", "Occasional", "Common", "Abundant")), x=total), stat='identity') +
  labs(y = " ", x = "Total Count") +
  theme(panel.background = element_rect(fill = "white", colour = "white",size = 2, linetype = "solid"), panel.grid.major = element_line(size = 0.5, linetype = 'solid',colour = "white"), panel.grid.minor = element_line(size = 0.25, linetype = 'solid',colour = "white")) +
  guides(fill = guide_legend(title.position = "top", title = "Abundance"))+
  labs(title = "Plant and Animal Abundance in National Parks", subtitle = "What are the most abundant threatened and endagered species in National Parks?") +
  theme(axis.text.y = element_text(color = "grey27"),axis.text.x = element_text(size = 10, color = "grey27"), axis.ticks.y = element_blank(), legend.position = "right", legend.justification = "left", plot.background = element_rect(fill ="peachpuff"), legend.background = element_rect(fill ="white"), legend.text = element_text(face="italic", color = "grey27"), legend.title = element_text(color = "grey27", face = "bold"), plot.title = element_text(face = "bold", size = 17, hjust = 0.5, color = "grey27"), plot.subtitle = element_text(face = "italic", size = 10, hjust = 0.5, color = "grey27"), plot.caption = element_text(face = "italic", color = "grey27")) +
  theme(axis.title.y=element_text(colour="grey27", face = "bold")) +
   theme(axis.title.x=element_text(colour="grey27", face = "bold"))


```

```{r message = FALSE, warning = FALSE}

## John

parksendanger <- speciesendanger %>% 
  group_by(`Park Name`, `Conservation Status`) %>% 
  summarize(count = n()) %>% 
  pivot_wider(names_from = `Conservation Status`, values_from = count, values_fill = 0) %>% 
  left_join(parks) %>% 
  select(`Park Code`, `Park Name`, Acres, Endangered, `In Recovery`, `Species of Concern`, `Under Review`, Threatened, `Proposed Threatened`, Extinct, `Proposed Endangered`)

# Size of park does not seem to be related to how many species of concern there are in the park!

ggplot(parksendanger, aes(x = reorder(`Park Code`, Acres), y = Acres, fill = `Species of Concern`)) + 
  geom_bar(stat = "identity") + 
  theme(axis.text.x = element_text(angle = 90, size = 6)) + 
  labs(x = "Park Code", y = "Park Size (Acres)", fill = "# Species of\nConcern") +
  scale_fill_continuous(type = "viridis") + 
  scale_y_continuous(labels = c(0, "2 mil.", "4 mil.", "6 mil.", "8 mil."))

parksendanger2 <- speciesendanger %>% 
  group_by(`Park Name`, `Conservation Status`) %>% 
  summarize(count = n()) %>% 
  pivot_wider(names_from = `Conservation Status`, values_from = count, values_fill = 0) %>% 
  left_join(parks) %>% 
    filter(Acres < 3000000) %>% 
  select(`Park Code`, `Park Name`, Acres, Endangered, `In Recovery`, `Species of Concern`, `Under Review`, Threatened, `Proposed Threatened`, Extinct, `Proposed Endangered`)

ggplot(parksendanger2, aes(x = reorder(`Park Code`, Acres), y = Acres, fill = `Species of Concern`)) + 
  geom_bar(stat = "identity") + 
  theme(axis.text.x = element_text(angle = 90, size = 6)) + 
  labs(x = "Park Code", y = "Park Size (Acres)", fill = "# Species of\nConcern") +
  scale_fill_continuous(type = "viridis")+ 
  scale_y_continuous(labels = c(0, "1 mil.", "2 mil.", "3 mil."))

# Money for parks is generally allocated to states, rather than parks, right? Maybe we look at states that have more than one park, to see if that state would require more focus

parkstate <- speciesendanger %>% 
  group_by(`Park Name`, `Conservation Status`) %>% 
  summarize(count = n()) %>% 
  pivot_wider(names_from = `Conservation Status`, values_from = count, values_fill = 0) %>% 
  left_join(parks) %>% 
  select(`Park Code`, `Park Name`, State, Acres, Endangered, `In Recovery`, `Species of Concern`, `Under Review`, Threatened, `Proposed Threatened`, Extinct, `Proposed Endangered`) %>% 
  separate(State, c("State1", "State2", "State3"), sep = ", ") %>% 
  pivot_longer(cols = c(State1, State2, State3), names_to = "State Type", values_to = "State") %>% 
  filter(!is.na(State))

statevalues <- parkstate %>% 
  group_by(State) %>% 
  summarize(Concern = sum(`Species of Concern`), ConcernAvg = mean(`Species of Concern`), Count = n()) %>% 
  mutate(ConcernAvg = round(ConcernAvg, 2))

# AK and CA both have 8 parks, but their species of concern numbers are way different!

ggplot(statevalues, aes(x = reorder(State, Count), y = Count, fill = ConcernAvg)) + 
  geom_bar(stat = "identity") + 
  labs(fill = "Average # Species\nof Concern Per\nPark", x = "State") + 
  scale_fill_gradient(low = "#C33764", high = "#1D2671") + 
  theme_light() + 
  scale_y_continuous(breaks = 0:8)

```

## Data Pitfalls

```{r message = FALSE}
## John

specieslargeviz <- speciesendanger %>% 
  filter(!is.na(Abundance)) %>% 
  group_by(Abundance, `Conservation Status`) %>% 
  summarize(count = n()) %>% 
  filter(!is.na(`Conservation Status`))

speciesconservationviz <- speciesendanger %>% 
  group_by(`Conservation Status`) %>% 
  summarize(count = n()) %>% 
  filter(!is.na(`Conservation Status`)) %>% 
  arrange(desc(count)) %>% 
  mutate(perc = (count / sum(count)) * 100) %>% 
  mutate(ypos = cumsum(perc)- 0.4*perc ) %>% 
  mutate(perc2 = round(perc, 1)) %>% 
  mutate(perc3 = paste0(perc2, "%"))

speciesabundanceviz <- speciesendanger %>% 
  filter(!is.na(Abundance)) %>% 
  group_by(Abundance) %>% 
  summarize(count = n())

# Here is where the visualization begins!

ggplot(speciesconservationviz, aes(x = "", y = perc, fill = reorder(`Conservation Status`, count), label = perc3)) +
  geom_bar(stat = "identity", width = 1, color = "white") + 
  coord_polar("y", start = 0) + 
  theme_void() + 
  scale_fill_manual(values = c("#8F0F1B", "#BE3ACD", "#304F9B", "#C7DD91", "#48A421", "#69EF7B", "#11CCDC", "black"),
                    breaks = c("Species of Concern", "Endangered", "Under Review", "Threatened", "In Recovery", "Proposed Endangered", "Proposed Threatened", "Extinct")) +
  geom_text(aes(y = ypos), color = "white", size = 6, check_overlap = TRUE) + 
    labs(fill = "Conservation Status", 
         title = "How Often Are Species Assigned Each Conservation Status?", 
         caption = "Overwhelmingly, species are placed in the 'Species of Concern' category,\nfar outweighing the next highest category: 'Endangered', at 6.8%.\nThis data excludes any species that are not given a category.\n(Including species not in danger of extinction).")

ggplot(speciesabundanceviz, aes(x = "", y = count, fill = reorder(Abundance, count))) + 
  geom_bar(stat = "identity", width = 1, color = "white") + 
  coord_polar("y", start = 0) + 
  theme_void() +
  scale_fill_manual(values = c("#99DEF9", "#A53460", "#56EBD3", "#284E37", "#E4997F", "#84EE15"), 
                    breaks = c("Uncommon", "Rare", "Common", "Unknown", "Occasional", "Abundant")) + 
  labs(fill = "Abundance",
       title = "How Often Are Species Assigned Each Abundance level?", 
       caption = "Where I had expected this data to show the same overwhelming trend in\n'Uncommon' species, it shows no overwhelming categorizations.\nLike the first graphic, this data set excludes species without\nAbundance levels, as well as those without Conservation Statuses,\nas the data we are analyzing regards primarily endangered species.")

ggplot(speciesabundanceviz, aes(x = reorder(Abundance, -count), y = count, fill = Abundance)) + 
  geom_bar(stat = "identity", show.legend = FALSE) +
  theme_classic() +
  scale_fill_manual(values = c("#84EE15", "#56EBD3", "#E4997F", "#A53460", "#99DEF9", "#284E37")) + 
  labs(x = "Abundance", 
       title = "A Clearer Look at Abundance Levels", 
       caption = "This graphic more clearly shows the actual trends in Abundance levels, using the same data as the previous graphic.")

```

```{r}

#Tommy

finalvis <- species %>% 
  filter(Occurrence != "Not Confirmed", !Abundance %in% c("Native", "Not Native"), !`Conservation Status` %in% c("Under Review", "In Recovery", "Extinct")) %>% 
  mutate(`Conservation Status` = case_when(`Conservation Status` %in% c("Species of Concern", "Endangered", "Threatened", "Proposed Threatened", "Proposed Endangered") ~ "Species of Concern")) %>% 
  mutate(`Conservation Status` = replace_na(`Conservation Status`, "Not of Concern")) 
  

head(finalvis)
```

```{r}

#Tommy

speciesnewabundance <- speciesnew %>% 
   filter(!is.na(`Abundance`), `Category` != "Vascular Plant") %>% 
  group_by(Category, Abundance, `Conservation Status`) %>% 
  summarize(total = n()) 
  
speciesnewabundance %>% group_by(Category) %>% mutate(Grandtotal = sum(total)) %>% ungroup() %>% mutate(Category = fct_reorder(Category,Grandtotal)) %>% ggplot() + geom_col(aes(y = Category, x = total, fill = `Conservation Status`)) +
  labs(y = " ", x = "Total Count") +
  theme(panel.background = element_rect(fill = "white", colour = "white",size = 2, linetype = "solid"), panel.grid.major = element_line(size = 0.5, linetype = 'solid',colour = "white"), panel.grid.minor = element_line(size = 0.25, linetype = 'solid',colour = "white")) +
  guides(fill = guide_legend(title.position = "top", title = "Level of Concern"))+
  labs(title = "Plant and Animal Abundance in National Parks") +
  theme(axis.text.y = element_text(color = "grey27"),axis.text.x = element_text(size = 10, color = "grey27"), axis.ticks.y = element_blank(), legend.position = "right", legend.justification = "left", plot.background = element_rect(fill ="peachpuff"), legend.background = element_rect(fill ="white"), legend.text = element_text(face="italic", color = "grey27"), legend.title = element_text(color = "grey27", face = "bold"), plot.title = element_text(face = "bold", size = 17, hjust = 0.5, color = "grey27"), plot.subtitle = element_text(face = "italic", size = 10, hjust = 0.5, color = "grey27"), plot.caption = element_text(face = "italic", color = "grey27")) +
  theme(axis.title.y=element_text(colour="grey27", face = "bold")) +
   theme(axis.title.x=element_text(colour="grey27", face = "bold")) +
  scale_fill_manual(values = c("darkseagreen4", "salmon"))





```



Gwen (Sorry!)
```{r}

library(ggmap) #install.packages("ggmap")
library(rstudioapi) #install.packages("rstudioapi")
library(mapview) #install.packages("mapview")

#########################################

mapview(parks, xcol = "Longitude", ycol = "Latitude", crs = 4269, grid = FALSE)

```

```{r}
#Tommy working on map

speciespark <- parks %>% 
  full_join(species)

speciespark2 <- speciespark %>% 
filter(Occurrence != "Not Confirmed", !Abundance %in% c("Native", "Not Native"), !`Conservation Status` %in% c("Under Review", "In Recovery", "Extinct")) %>% 
  mutate(`Conservation Status` = case_when(`Conservation Status` %in% c("Species of Concern", "Endangered", "Threatened", "Proposed Threatened", "Proposed Endangered") ~ "Species of Concern")) %>% 
  mutate(`Conservation Status` = replace_na(`Conservation Status`, "Not of Concern")) %>% 
  mutate(total = n()) %>% 
  
  #I want to do "Species of Concern" over "total"

head(speciespark2)
```


```{r message = FALSE}
statevaluesmap <- statevalues %>% 
  full_join(states) %>% 
   mutate(state_name = str_to_lower(abbr2state(State)))

statevaluesmap %>%
  ggplot() +
  geom_map(
    map = fifty_states,
    aes(
      map_id = state_name,
      fill = ConcernAvg
    )
  ) +
  expand_limits(x = map_data("state")$long, y = map_data("state")$lat) + 
  theme_void()

statevaluesmap %>%
  ggplot() +
  geom_map(
    map = fifty_states,
    aes(
      map_id = state_name,
      fill = Concern
    )
  ) +
  expand_limits(x = map_data("state")$long, y = map_data("state")$lat) + 
  theme_void()

statevaluesmap %>%
  ggplot() +
  geom_map(
    map = fifty_states,
    aes(
      map_id = state_name,
      fill = Count
    )
  ) +
  expand_limits(x = map_data("state")$long, y = map_data("state")$lat) + 
  theme_void()
```
